import Groq from 'groq-sdk'
import dotenv from 'dotenv'
import { fetchPRDiff, postReviewComment } from './github.js'

dotenv.config()

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY })

// ── Agent 1: Security Auditor ──────────────────────────────────────
async function runSecurityAgent(diff) {
  const response = await groq.chat.completions.create({
    model: 'llama-3.3-70b-versatile',
    messages: [
      {
        role: 'system',
        content: `You are a strict Security Auditor reviewing a GitHub Pull Request diff. 
Your ONLY job is to find security vulnerabilities. Look for:
- SQL injection risks
- Exposed API keys or secrets hardcoded in the code
- Authentication or authorization flaws
- XSS vulnerabilities
- Insecure dependencies
- Sensitive data being logged or exposed
Respond in this exact format:
SECURITY FINDINGS:
- [finding 1]
- [finding 2]
If nothing is found, write: SECURITY FINDINGS: No issues found.`
      },
      {
        role: 'user',
        content: `Review this code diff:\n\`\`\`\n${diff}\n\`\`\``
      }
    ],
    max_tokens: 500
  })
  return response.choices[0].message.content
}

// ── Agent 2: Performance Optimizer ────────────────────────────────
async function runPerformanceAgent(diff) {
  const response = await groq.chat.completions.create({
    model: 'llama-3.3-70b-versatile',
    messages: [
      {
        role: 'system',
        content: `You are a Performance Optimizer reviewing a GitHub Pull Request diff.
Your ONLY job is to find performance issues. Look for:
- Unnecessary loops or nested loops (O(n²) complexity)
- Missing database indexes or inefficient queries
- Memory leaks or unnecessary object creation
- Blocking synchronous operations that should be async
- Redundant API calls or computations
Respond in this exact format:
PERFORMANCE FINDINGS:
- [finding 1]
- [finding 2]
If nothing is found, write: PERFORMANCE FINDINGS: No issues found.`
      },
      {
        role: 'user',
        content: `Review this code diff:\n\`\`\`\n${diff}\n\`\`\``
      }
    ],
    max_tokens: 500
  })
  return response.choices[0].message.content
}

// ── Agent 3: Lead Developer ────────────────────────────────────────
async function runLeadDevAgent(diff) {
  const response = await groq.chat.completions.create({
    model: 'llama-3.3-70b-versatile',
    messages: [
      {
        role: 'system',
        content: `You are a Lead Developer reviewing a GitHub Pull Request diff.
Your ONLY job is to check code quality, logic, and maintainability. Look for:
- Unclear variable or function names
- Missing error handling
- Duplicated code that should be refactored
- Logic errors or edge cases not handled
- Missing comments on complex logic
- Functions doing too many things at once
Respond in this exact format:
CODE QUALITY FINDINGS:
- [finding 1]
- [finding 2]
If nothing is found, write: CODE QUALITY FINDINGS: No issues found.`
      },
      {
        role: 'user',
        content: `Review this code diff:\n\`\`\`\n${diff}\n\`\`\``
      }
    ],
    max_tokens: 500
  })
  return response.choices[0].message.content
}

// ── Orchestrator ───────────────────────────────────────────────────
export async function runAgentPipeline(prData) {
  console.log('Fetching PR diff...')
  const diff = await fetchPRDiff(prData)

  if (!diff) {
    console.log('No diff found, skipping.')
    return
  }

  console.log('Running all three agents in parallel...')

  const [securityFindings, performanceFindings, codeQualityFindings] = await Promise.all([
    runSecurityAgent(diff),
    runPerformanceAgent(diff),
    runLeadDevAgent(diff),
  ])

  console.log('Agents done. Compiling final review...')

  const finalComment = `## 🤖 Multi-Agent PR Review

> This review was automatically generated by 3 specialized AI agents.

---

### 🔒 Security Auditor
${securityFindings}

---

### ⚡ Performance Optimizer
${performanceFindings}

---

### 🧠 Lead Developer
${codeQualityFindings}

---
*Powered by Llama 3.3 70B + Multi-Agent Orchestration*`

  console.log('Posting review comment to GitHub...')
  await postReviewComment(prData, finalComment)
  console.log(`✅ Review posted on PR #${prData.number}`)
}